modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/colossal-dungeons/colossal-dungeons/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "[4.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "optional"
versionRange = "[9.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "smartbrainlib"
type = "optional"
versionRange = "[1.14,)"
ordering = "AFTER"
side = "BOTH"
